---
- name: Men&Mice users test play
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Get the free IP address and show info
      debug:
        msg:
          - "Ansible version    : {{ ansible_version.full }}"
          - "Python version     : {{ ansible_facts['python_version'] }}"
          - "Python executable  : {{ ansible_facts['python']['executable'] }}"

    - name: Add the user 'johnd' as an admin
      mm_user:
        username: johnd
        password: password
        full_name: John Doe
        state: present
        authentication_type: internal
        roles:
          - Administrators (built-in)
          - DNS Administrators (built-in)
          - DHCP Administrators (built-in)
          - IPAM Administrators (built-in)
          - User Administrators (built-in)
          - Approvers (built-in)
          - Requesters (built-in)
        provider: "{{ provider }}"
